import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.IntervalCategoryDataset;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;


public class Main extends JFrame {

    DefaultTableModel tableModel;

    /**
     * Creates new form JTable
     */
    public Main() {
        initComponents();

        tableModel = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ScheduleName = new javax.swing.JLabel();
        AWT = new javax.swing.JLabel();
        ATAT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("panel"); // NOI18N
        setUndecorated(true);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Process", "Color", "Name", "PID", "Priority"
                }
        ));
        jTable1.setToolTipText("Process");
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setEditingColumn(1);
        jTable1.setEditingRow(1);
        jTable1.setName("panel"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Schedule Name: ");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AWT: ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ATAT: ");

        ScheduleName.setForeground(new java.awt.Color(255, 255, 255));
        ScheduleName.setText("sn");

        AWT.setForeground(new java.awt.Color(255, 255, 255));
        AWT.setText("0.0");

        ATAT.setForeground(new java.awt.Color(255, 255, 255));
        ATAT.setText("0.0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Statistics");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ATAT))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ScheduleName))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AWT)))
                                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(ScheduleName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(AWT))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(ATAT))
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Processes Information");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 705, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                        .addGap(401, 401, 401)
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(24, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 487, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addContainerGap(705, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(141, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(359, 359, 359))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        pack();
    }// </editor-fold>




    public static int menu() {
        int num;

        System.out.println("1- SJF");
        System.out.println("2- SRTF");
        System.out.println("3- Priority Scheduler ");
        System.out.println("4- AG Scheduler ");

        Scanner input = new Scanner(System.in);
        num = input.nextInt();

        return num;

    }

    public static void main(String args[]) {

        Main mainMethod = new Main();

        ArrayList<Process> processArrayList = new ArrayList<>();
        String name;
        String color;
        int arrivalTime;
        int burstTime;
        int priorityNum;

        Scanner input = new Scanner(System.in);

        int numOfProcess;
        int rrQuantum;
        int contextProcess;
        int choiceNum;



        System.out.println("Enter number of process");
        numOfProcess = input.nextInt();


        System.out.println("Enter Context Switching ");
        contextProcess = input.nextInt();

        for (int i = 0; i < numOfProcess; i++) {
            System.out.println("Enter process name");
            name = input.next();
            System.out.println("Enter process color");
            color = input.next();
            System.out.println("Enter process arrival time");
            arrivalTime = input.nextInt();
            System.out.println("Enter process burst time");
            burstTime = input.nextInt();
            System.out.println("Enter process priority");
            priorityNum = input.nextInt();
            System.out.println("Enter process quantum");
            rrQuantum = input.nextInt();

            Process p = new Process(name, color, arrivalTime, burstTime, priorityNum, rrQuantum);
            processArrayList.add(p);
        }




        choiceNum = menu();

        if (choiceNum == 1){
            SJF  sjf = new SJF ( processArrayList );
            sjf.startScheduling ();
            System.out.println ("Average Waiting time : "+ sjf.getAverageTurnaroundTime () );
            System.out.println ("Average Turnaround time : "+sjf.getAverageTurnaroundTime () );
            mainMethod.AWT.setText(sjf.getAverageTurnaroundTime () + "");
            mainMethod.ATAT.setText("" + sjf.getAverageTurnaroundTime ());

        }

        if (choiceNum == 2){


        }

        if (choiceNum == 3){
            PriorityScheduling pScheduling = new PriorityScheduling(processArrayList,contextProcess);
            pScheduling.start();
            System.out.println( "\nAverage Waiting Time :  " + pScheduling.getAverageWaiting());
            System.out.println("Average Turnaround Time :" + pScheduling.getAverageTurnAround() + "\n");
        }

        if (choiceNum == 4) {
            AGAT a = new AGAT(processArrayList);
            a.printInfo();
            for(int i = 0; i < processArrayList.size(); i++){
                System.out.print(processArrayList.get(i).getName() +" Factor- ");
                for(int j =0; j<processArrayList.get(i).AGAT.size(); j++){
                    System.out.print(processArrayList.get(i).AGAT.get(j)+" ");
                }
                System.out.println();
                System.out.print(processArrayList.get(i).getName() +" Quantum- ");
                for(int j =0; j<processArrayList.get(i).quantumTime.size(); j++){
                    System.out.print(processArrayList.get(i).quantumTime.get(j)+" ");
                }
                System.out.println();
            }
        }

        for(int i = 0; i < processArrayList.size(); i++){
            System.out.print(processArrayList.get(i).getName() +" Factor- ");
            for(int j =0; j<processArrayList.get(i).AGAT.size(); j++){
                System.out.print(processArrayList.get(i).AGAT.get(j)+" ");
            }
            System.out.println();
            System.out.print(processArrayList.get(i).getName() +" Quantum- ");
            for(int j =0; j<processArrayList.get(i).quantumTime.size(); j++){
                System.out.print(processArrayList.get(i).quantumTime.get(j)+" ");
            }
            System.out.println();
        }

        mainMethod.ScheduleName.setText("ABCSchedule");

        for (Process process : processArrayList) {
            mainMethod.tableModel.addRow(new Object[]{
                    processArrayList.indexOf(process), process.getColor(), process.getName(), process.getpID(), process.getPriority()
            });
        }

        GanttChart gc = new GanttChart("CPU scheduling", processArrayList);


        mainMethod.tableModel.fireTableDataChanged();
        mainMethod.setLocationRelativeTo(null);
        mainMethod.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        mainMethod.setVisible(true);

    }







    // Variables declaration - do not modify
    private javax.swing.JLabel ATAT;
    private javax.swing.JLabel AWT;
    private javax.swing.JLabel ScheduleName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration
}

